# MATRIX OPERATIONS

In [1]:
import numpy as np

In [2]:
#Matrix creation
matrix_1=np.array([[2,3],[4,5]])
print(matrix_1)

[[2 3]
 [4 5]]


In [3]:
#matrix shape
matrix_1.shape

(2, 2)

In [7]:
#Creating random matrix
np.random.seed(10)
matrix_2=np.random.randn(3,3)
print(matrix_2)

[[ 1.3315865   0.71527897 -1.54540029]
 [-0.00838385  0.62133597 -0.72008556]
 [ 0.26551159  0.10854853  0.00429143]]


In [12]:
#matrix with less than 100 and integers
np.random.seed(10)
matrix3=np.random.randint(100,size=(3,3))
print(matrix3)

[[ 9 15 64]
 [28 89 93]
 [29  8 73]]


In [14]:
#Matrix with all values are is 1
matrix_4=np.ones((3,3),dtype=int)
print(matrix_4)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [19]:
#Null matrix
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
#identy matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
#Transpose of a matrix
transpose_matrix_3=np.transpose(matrix_3)
print(transpose_matrix_3)

[[ 9 28 29]
 [15 89  8]
 [64 93 73]]


In [23]:
matrix_1

array([[2, 3],
       [4, 5]])

In [24]:
matrix_5=np.array([[5,6],[6,7]])
matrix_5

array([[5, 6],
       [6, 7]])

In [25]:
#Addition
matrix_1+matrix_5

array([[ 7,  9],
       [10, 12]])

In [26]:
#Substraction
matrix_1-matrix_5

array([[-3, -3],
       [-2, -2]])

In [29]:
#Multiplication with Scalar
x=5
product=np.multiply(x,matrix_1)
print(product)

[[10 15]
 [20 25]]


In [31]:
# Multiplication of two matrix
#dot product
np.dot(matrix_1,matrix_5)

array([[28, 33],
       [50, 59]])

In [32]:
#Element wise multiplication
np.multiply(matrix_1,matrix_5)

array([[10, 18],
       [24, 35]])