# NUMPY OPERATIONS

In [2]:
import numpy as np

In [6]:
#converting list into array
list=[1,2,3,4]
np.array(list)

array([1, 2, 3, 4])

In [9]:
#nested list
nested_list=[[1,2,3],['a','b','c'],['a','b','c']]
np.array(nested_list)

array([['1', '2', '3'],
       ['a', 'b', 'c'],
       ['a', 'b', 'c']], dtype='<U11')

In [12]:
#BUILT IN FUNCTIONS
#np.arange(start,end(excluded),step)
np.arange(0,10,1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [13]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [16]:
#all Zeros
#np.zeros(rows,columns)
#for datatype  np.zeros((rows,columns),dtype=)
np.zeros((3,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [17]:
#all ones
#np.ones(rows,columns)
#for datatype  np.ones((rows,columns),dtype=)
np.ones((3,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [21]:
#linspace --> Values prints equally spaced
#np.linspace((start,end,how many values)
np.linspace(1,10,30)

array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ])

In [26]:
#Identity matrix and dtype not supported
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [116]:
#random matrix
#np.random.rand(rows,columns) 
np.random.rand(2,3)

array([[0.19806286, 0.76053071, 0.16911084],
       [0.08833981, 0.68535982, 0.95339335]])

In [118]:
#to get same Values to again doing random values-->np.random.seed(10)
np.random.seed(10)
np.random.rand(2,3)

array([[0.77132064, 0.02075195, 0.63364823],
       [0.74880388, 0.49850701, 0.22479665]])

In [31]:
#both +ve and -ve values 
np.random.randn(2,3)

array([[-0.08566145, -0.75063417,  0.27761554],
       [-0.88478254,  0.20110215, -0.05314326]])

In [34]:
#printing random value using dtypes
#np.random.randint(start,end(excudes))
np.random.randint(1,100)

6

In [35]:
#np.random.randint(start,end(excudes),step)
np.random.randint(1,100,10)

array([25, 47, 78, 34, 24, 26, 79, 88, 49, 96])

In [37]:
#reshape--> returning an array containg data with new data
#reshape(rows,colums)
arr=np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [42]:
arr2=np.arange(0,50,10)
arr2

array([ 0, 10, 20, 30, 40])

In [43]:
# argmax-->index of maximum value
arr2.argmax()

4

In [44]:
# argmin-->index of minimum value
arr2.argmin()

0

In [48]:
# min()-->minimum value
arr2.min()

0

In [47]:
#max()-->maximum value
arr2.max()

40

In [55]:
# [start:end:step]-->Bracket indexing
#0th index postion
a=arr2[0]
#[atart:end]-->where you want start and end
b=arr2[3:6]
#reverse order
c=arr2[::-1]
a

0

In [56]:
b

array([30, 40])

In [57]:
c

array([40, 30, 20, 10,  0])

In [68]:
#Broadcasting-->it assigns the values to many positions like list but in list only one index position
arr3=np.arange(0,11)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
#prints which values wants to assign same values
slicing_array=arr3[0:5]
slicing_array

array([0, 1, 2, 3, 4])

In [70]:
#sliced values assigning to 100
slicing_array[:]=100
slicing_array

array([100, 100, 100, 100, 100])

In [71]:
arr3

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [74]:
#Indexing 2D array
mat=np.array([[1,2,3],[4,5,6],[9,5,3]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [9, 5, 3]])

In [76]:
mat.shape

(3, 3)

In [77]:
mat[2][2]

3

In [79]:
#[start row:end row(excludes),start column:ending column(excludes)]
mat[1:,1:]

array([[5, 6],
       [5, 3]])

In [80]:
#Boolean indexing--> True or False
arr4=np.arange(1,15)
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [81]:
arr4>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [82]:
boolean_array=arr4>5
arr4[boolean_array]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [84]:
arr4[arr4>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [85]:
##Numpy Operations

In [86]:
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [87]:
#addition
arr4+arr4

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [88]:
#subtraction
arr4-arr4

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [89]:
#multiplication
arr4*arr4

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196])

In [91]:
#power
arr4**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196], dtype=int32)

In [93]:
np.sqrt(arr4)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [94]:
np.exp(arr4)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06])

In [95]:
np.max(arr4)

14

In [96]:
np.sin(arr4)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111,
       -0.99999021, -0.53657292,  0.42016704,  0.99060736])

In [97]:
##Statistical Operations
arr5=np.random.randint(0,25,6)
arr5

array([23, 24, 15, 22,  1, 12])

In [98]:
arr5.mean()

16.166666666666668

In [101]:
arr5.var()

65.13888888888889

In [102]:
arr5.std()

8.070866675202167

In [103]:
np.median(arr5)

18.5

In [104]:
##using numpy as list

In [106]:
l=[1,2,3]
l*2

[1, 2, 3, 1, 2, 3]

In [107]:
l*2.5

TypeError: can't multiply sequence by non-int of type 'float'

In [114]:
np_1=np.array(l)
np_1*2.5

array([2.5, 5. , 7.5])